### PR TITLE
implemented IncludeDays handling to limit the size of the backup history to be evaluated

### PR DESCRIPTION
**Pull request by ronnybremer**

### CODE REVIEW

**Comment by ronnybremer** [comment]
This pull request also incorporates the fix proposed here: https://github.com/Icinga/icinga-powershell-mssql/pull/38

**Comment by ronnybremer** [comment]
CA signed

**Comment by bobapple** [comment]
@cla-bot check

**Comment by LordHepipud** [comment]
Thank you for the PR! Could you please squash all the commits to one and rebase it for the current master? The issue PR was already merged.

Please also update the `changelog` before squashing on the `Enhancements` area with:

```
* [42](https://github.com/Icinga/icinga-powershell-mssql/pull/42) Adds option for `IncludeDays` to reduce the amount of backup data generated
```

and also generate the new plugin configuration with `Publish-IcingaForWindowsComponent -Name 'mssql'` by using Icinga PowerShell Framework v1.9.0.

**Comment by LordHepipud** [comment]
Thanks!

**Comment by ronnybremer** [comment]
Thank you for the commit. I am sorry, I must have missed the email from May, I just saw it.

Also, tbh, I wouldn’t have known how to “squash and rebase”, I hope it was still usable for you. Would love to learn that though :)

Yours,

Ronny

**Comment by LordHepipud** [comment]
It's all fine - I missed this topic entirely and just saw it while I was preparing the next release for 30th August 😄
Personally I use Visual Studio Code, which has a great integration for git and GitHub, making editing and managing or PR's, commits and everything related super easy.

**Pull request merged**
